console.write("hello")
console.write("hello")console.write("hello")console.write("hello")
console.write("hello")
console.write("hello")
console.write("hello")
console.write("hello")console.write("hello")
console.write("hello")